### ISSUE TITLE
Set uid and gui on start_program in check

### ISSUE THREAD

**Issue by lucasslima** [poise/poise-monit#26]
Hi,

I tried to set the uid and gid on the start_program property, but the resource ignored it. It be possible to run the start_program as a especified user?

**Comment by coderanger** [comment]
Assuming you mean the `monit_check` resource, no it doesn't have specific support for this as it is very very simple. You would want to use the more generic `monit_config` resource which takes either a template or block of text directly so you can do anything Monit supports.

**Comment by lucasslima** [comment]
I see. That's probably a better way. Would be nice to be able to do it in the monit_check though. Thank for the head's up!

**Comment by coderanger** [comment]
`monit_check` is specifically aimed at the use case of "I want to use Monit to watch a service from a distro package (or equivalent)". Since the commands for that will always be run as root it's probably outside of the scope. By the time you're making something that custom it's going to be clearer to just write it in-line I bet :)

Since I noticed I don't have an example of that in the readme:

```ruby
monit_config 'myservice' do
  content <<-EOH
whatever config
you want can
go here
EOH
end
```
